version: '3.8'

services:
  postgres1:
    image: postgres:15-alpine
    container_name: "postgres1"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres


  postgres2:
    image: postgres:15-alpine
    container_name: "postgres2"
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres


  postgres3:
    image: postgres:15-alpine
    container_name: "postgres3"
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres


  web-admin:
    build:
      context: ./back/web-admin
      dockerfile: Dockerfile
    container_name: web-admin
    depends_on:
      - postgres1
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres1:5432/postgres'
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: 'org.hibernate.dialect.PostgreSQLDialect'
    ports:
      - "8080:8080"


  web-product:
    build:
      context: ./back/web-product
      dockerfile: Dockerfile
    hostname: web-product
    container_name: web-product
    depends_on:
      - postgres3
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres3:5432/postgres'
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: 'org.hibernate.dialect.PostgreSQLDialect'
    ports:
      - "8082:8082"


  web-order:
    build:
      context: ./back/web-order
      dockerfile: Dockerfile
    container_name: web-order
    depends_on:
      - postgres2
      - web-product
    environment:
      URL_PRODUCT: 'web-product:8082'
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres2:5432/postgres'
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: 'org.hibernate.dialect.PostgreSQLDialect'
    ports:
      - "8081:8081"


  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - web-admin
      - web-order
      - web-product