
create table users (
    id bigint generated by default as identity,
    email varchar(30) not null UNIQUE,
    password varchar(255) not null,
    primary key (id)
);


INSERT into users (email, password)
VALUES ('User1@gmail.com','$2a$10$ULvp1clg5NwqB6XS3D8aguysSc'),
       ('User2@gmail.com', '$2a$10$ULvp1clg5NwqB6XS3D8aguysSc')

