
create table users (
    id bigint generated by default as identity,
    email varchar(30) not null UNIQUE,
    password varchar(255) not null,
    primary key (id)
);


INSERT into users (email, password)
VALUES ('user@mail.ru','$2a$10$hmb9wIWXry3p6sTNqgQ8Q.nYNHdK6Fl74mKlLseTxMhz6NF.BFldC')


